development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3


# default: &default
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
# development:
#   <<: *default
#   url: "postgresql://postgres:postgres@localhost:5432/carhire-data"
# test:
#   <<: *default
#   url: "postgresql://postgres:postgres@localhost:5432/test_carhire-data"
# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>